# Generated by Django 5.0.6 on 2024-06-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_alter_client_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly_token', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='UserCalendlyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mentor')),
            ],
        ),
    ]
