# Generated by Django 5.0.6 on 2024-06-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCalendlyEmail',
        ),
    ]
