# Generated by Django 5.0.6 on 2024-06-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_alter_client_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(max_length=142, verbose_name='Titulo de la plantilla')),
                ('email_template', models.TextField(verbose_name='Plantilla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mentor')),
            ],
        ),
    ]
