# Generated by Django 5.0.6 on 2024-06-09 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mentor'),
        ),
    ]
