# Generated by Django 5.0.6 on 2024-08-17 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_mentor'),
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=120, unique=True)),
                ('folder_name', models.CharField(max_length=120, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mentor')),
            ],
        ),
    ]
